# Generated by Django 3.2.9 on 2021-12-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20211210_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=30, null=True),
        ),
    ]
