# Generated by Django 3.2.9 on 2021-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_patient',
            field=models.BooleanField(default=True, verbose_name='is_patient'),
        ),
    ]
