# Generated by Django 3.2.9 on 2021-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_is_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_FeNEeKk.png', upload_to='profile_pics'),
        ),
    ]
