# Generated by Django 3.2.9 on 2022-01-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalApp', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Users.doctor'),
        ),
        migrations.AddField(
            model_name='record',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.hospital'),
        ),
        migrations.AddField(
            model_name='record',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Users.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.hospital'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Record_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.record'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Admin_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Users.administrator'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Users.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Record_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.record'),
        ),
    ]
