# Generated by Django 3.2.9 on 2021-12-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('MedicalApp', '0002_hospital_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_Details', models.TextField()),
                ('Appointment_Schedule', models.DateField(auto_now_add=True)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Users.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.hospital')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription_Details', models.TextField()),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Users.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.hospital')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Diagnosis', models.TextField()),
                ('Record_Date', models.DateField(auto_now_add=True)),
                ('Appointment_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.appointment')),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Users.doctor')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.hospital')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient')),
                ('Prescription_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.prescription')),
            ],
        ),
    ]
