# Generated by Django 3.2.9 on 2022-01-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0003_hospitalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='aboutHospital',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
