# Generated by Django 3.2.9 on 2021-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0003_appointment_prescription_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_Schedule',
            field=models.DateField(),
        ),
    ]
