# Generated by Django 3.2.9 on 2021-12-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0004_alter_appointment_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Appointment_ID',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Prescription_ID',
        ),
    ]
