# Generated by Django 3.2.9 on 2021-12-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0005_auto_20211218_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Record_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='Record_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='MedicalApp.record'),
            preserve_default=False,
        ),
    ]
