# Generated by Django 3.2.9 on 2021-12-18 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0006_auto_20211218_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Record_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
