# Generated by Django 3.2.9 on 2021-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0007_alter_record_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_Schedule',
            field=models.DateTimeField(),
        ),
    ]
